#!/usr/bin/env pwsh
<#
  Grimdex first-run setup. Idempotent; safe to re-run.
    pwsh setup.ps1                          # verify structure + report junction states
    pwsh setup.ps1 -CreateJunction          # also swap ~/.claude/knowledge -> junction (asks first)
    pwsh setup.ps1 -LinkRules               # also swap ~/.claude/rules -> universal/claude-rules (asks first)
    pwsh setup.ps1 -CreateJunction -Force   # non-interactive (still refuses dirty trees / diverged rules)
    pwsh setup.ps1 -Examples operator       # fill missing config/*.json from the example operator setup
    pwsh setup.ps1 -Mode agents             # AGENTS.md mode: stamp the law into <dev root>/AGENTS.md + every wired project
    pwsh setup.ps1 -Mode classic            # back to GRIMDEX.md pointers (removes the main-level stamp)
    pwsh setup.ps1 -Update                  # pull Grimdex, then re-stamp/re-wire everything in the current mode
#>
param(
    [string]$KnowledgePath = (Join-Path $HOME '.claude' 'knowledge'),
    [string]$RulesPath = (Join-Path $HOME '.claude' 'rules'),
    [switch]$CreateJunction,
    [switch]$LinkRules,
    [switch]$ConfigureNetwork,
    [ValidateSet('operator', 'plain', 'skip')][string]$Examples,
    [ValidateSet('classic', 'agents')][string]$Mode,
    [string]$DevRoot,
    [switch]$Update,
    [switch]$Force
)
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'scripts' 'setup-lib.ps1')
. (Join-Path $PSScriptRoot 'scripts' 'wire-lib.ps1')
$root = $PSScriptRoot

# 0. -Update: pull first, so every later step works from the current Grimdex
if ($Update) {
    # Grimdex is itself a wired project: its own six agent files are regenerated by this
    # very step, so they never block an update.
    $generated = 'CLAUDE.md', 'AGENTS.md', 'GEMINI.md', 'GROK.md', '.cursorrules', '.github/copilot-instructions.md'
    if (git -C $root status --porcelain -- . ($generated | ForEach-Object { ":(exclude)$_" })) {
        throw "Grimdex has uncommitted changes in $root — commit and push them first; -Update never pulls over local work."
    }
    $before = git -C $root rev-parse HEAD
    git -C $root pull --ff-only
    if ($LASTEXITCODE -ne 0) { throw 'git pull --ff-only failed — resolve it by hand, then re-run -Update.' }
    if ((git -C $root rev-parse HEAD) -ne $before) {
        # The pull may have changed this script or its libraries, which are already loaded.
        # Re-run the pulled copy (its own pull is then a no-op) so the re-stamp uses new code.
        Write-Host '  Grimdex moved — re-running the updated setup.'
        & pwsh -NoProfile -File $PSCommandPath @PSBoundParameters
        exit $LASTEXITCODE
    }
}

# 1. Structure: tier dirs exist (no-op when already present)
foreach ($dir in 'projects', 'universal', 'config', 'scripts', 'docs') {
    New-Item -ItemType Directory -Force -Path (Join-Path $root $dir) | Out-Null
}

# 2. Root files: report, never overwrite
foreach ($f in 'GRIMDEX.md', 'KNOWLEDGE.md', 'README.md') {
    $ok = Test-Path (Join-Path $root $f)
    Write-Host ("  {0}  {1}" -f ($ok ? 'OK     ' : 'MISSING'), $f) -ForegroundColor ($ok ? 'Green' : 'Red')
    if (-not $ok) { Write-Warning "$f is missing — restore it from git before using this clone." }
}
if (-not (Test-GrimdexRoot -Root $root)) { throw "This directory is not a valid Grimdex root: $root" }

# 3. Mirrored global rules: sync state (single 'linked' row when the rules junction is live)
foreach ($r in (Sync-GrimdexRules -GrimdexRoot $root -RulesPath $RulesPath)) {
    Write-Host ("  rule {0,-16} {1}" -f $r.action, $r.rule)
    if ($r.action -eq 'conflict-skipped') {
        Write-Warning "$($r.rule): live copy differs from the Grimdex mirror — reconcile (update the mirror, or re-run sync with -Force via Sync-GrimdexRules)."
    }
}

# 4. Knowledge junction state + optional swap
$state = Get-GrimdexJunctionState -KnowledgePath $KnowledgePath -Target $root
Write-Host "  Junction: $KnowledgePath -> $root : $state"
if ($CreateJunction -and $state -ne 'linked') {
    $go = [bool]$Force
    if (-not $go) {
        Write-Host "  About to replace $KnowledgePath with a junction to $root."
        Write-Host "  The existing directory is kept as $KnowledgePath.bak (never deleted by this script)."
        $go = (Read-Host '  Proceed? [y/N]') -match '^[Yy]'
    }
    if ($go) {
        $result = Install-GrimdexJunction -KnowledgePath $KnowledgePath -Target $root -Force:$Force
        Write-Host ("  Junction {0}. Backup: {1}" -f $result.action, ($result.backup ?? 'n/a')) -ForegroundColor Green
    } else { Write-Host '  Skipped.' }
} elseif ($state -ne 'linked') {
    Write-Host '  (run again with -CreateJunction to link it)'
}

# 5. Rules junction (v2): ~/.claude/rules served FROM universal/claude-rules
$rulesMirror = Join-Path $root 'universal' 'claude-rules'
$rstate = (Test-Path $rulesMirror) ? (Get-GrimdexJunctionState -KnowledgePath $RulesPath -Target $rulesMirror) : 'no-mirror'
Write-Host "  Rules junction: $RulesPath -> $rulesMirror : $rstate"
if ($LinkRules -and $rstate -notin 'linked', 'no-mirror') {
    $go = [bool]$Force
    if (-not $go) {
        Write-Host "  About to replace $RulesPath with a junction to $rulesMirror."
        Write-Host "  The existing directory is kept as $RulesPath.bak (never deleted by this script)."
        $go = (Read-Host '  Proceed? [y/N]') -match '^[Yy]'
    }
    if ($go) {
        $result = Install-GrimdexRulesJunction -GrimdexRoot $root -RulesPath $RulesPath -Force:$Force
        Write-Host ("  Rules junction {0}. Backup: {1}" -f $result.action, ($result.backup ?? 'n/a')) -ForegroundColor Green
    } else { Write-Host '  Skipped.' }
} elseif ($rstate -in 'real-dir', 'missing') {
    Write-Host '  (run again with -LinkRules to serve rules directly from Grimdex)'
}

# 6. Operator network profile (dev-server bind/announce URLs)
# UserInteractive is always true on macOS/Linux, so also treat redirected stdin (agents,
# launchd, CI) and -Update (meant to run unattended) as non-interactive.
$nonInteractive = [bool]$Force -or [bool]$Update -or -not [Environment]::UserInteractive -or [Console]::IsInputRedirected
$net = Initialize-OperatorNetworkConfig -GrimdexRoot $root -Reconfigure:$ConfigureNetwork -NonInteractive:$nonInteractive
$netMode = $net.PSObject.Properties['mode']?.Value
$netReason = $net.PSObject.Properties['reason']?.Value
Write-Host ("  Operator network: {0}{1}" -f $net.action, $(if ($netMode) { " ($netMode)" } elseif ($netReason) { " — $netReason" } else { '' }))
if ($net.action -eq 'skipped') {
    Write-Host '  (copy config/operator-network.example.json → config/operator-network.json, or re-run without -Force)'
}

# 7. Missing instance configs: offer the example operator setup or the plain examples
$exParams = @{ GrimdexRoot = $root; NonInteractive = $nonInteractive }
if ($Examples) { $exParams.Choice = $Examples }
foreach ($e in @(Initialize-GrimdexExampleConfigs @exParams | Where-Object action -ne 'exists')) {
    Write-Host ("  config {0,-16} {1}" -f $e.action, $e.name)
}

# 8. Rules-file mode (classic = GRIMDEX.md pointers; agents = AGENTS.md carries the law)
$modeFile = Join-Path $root 'config' 'grimdex-mode.json'
$cur = Get-GrimdexMode -GrimdexRoot $root
$rewire = [bool]$Update
if ($Mode -or $DevRoot) {
    $cur = Set-GrimdexMode -GrimdexRoot $root -Mode ($Mode ? $Mode : $cur.mode) -DevRoot ($DevRoot ? $DevRoot : $cur.dev_root)
    $rewire = $true
} elseif (-not (Test-Path $modeFile) -and -not $nonInteractive) {
    Write-Host '  Rules file: [c]lassic — GRIMDEX.md is the rules file, projects point at it (default)'
    Write-Host '              [a]gents  — AGENTS.md carries the law; CLAUDE.md imports it, other tool files redirect'
    $a = Read-Host '  Which? [c/a]'
    $picked = if ($a -match '^[Aa]') { 'agents' } else { 'classic' }
    $d = Read-Host "  Dev root (the main level every project lives under) [$($cur.dev_root)]"
    $cur = Set-GrimdexMode -GrimdexRoot $root -Mode $picked -DevRoot ([string]::IsNullOrWhiteSpace($d) ? $cur.dev_root : $d)
    $rewire = $picked -eq 'agents'
}
Write-Host ("  Rules mode: {0}  (dev root: {1})" -f $cur.mode, $cur.dev_root)
if ($rewire) {
    $rw = @(Invoke-GrimdexRewire -GrimdexRoot $root -Mode $cur.mode -DevRoot $cur.dev_root)
    $changed = @($rw | Where-Object changed -gt 0)
    Write-Host ("  Re-wired {0} project(s) in {1} mode; {2} changed." -f @($rw | Where-Object project -ne '(main level)').Count, $cur.mode, $changed.Count) -ForegroundColor Green
    foreach ($c in $changed) { Write-Host ("    {0,2} file(s)  {1}" -f $c.changed, $c.project) }
    foreach ($e in @($rw | Where-Object error)) { Write-Warning "$($e.project): $($e.error)" }
    if ($changed.Count) { Write-Host '  Changed projects have uncommitted edits to their agent files — commit them from each repo.' }
} elseif ($cur.mode -eq 'agents') {
    $wired = @(Find-GrimdexWiredProjects -DevRoot $cur.dev_root)
    $stale = @($wired | Where-Object { (Test-GrimdexStamp -ProjectDir $_ -GrimdexRoot $root) -ne 'current' })
    $top = Join-Path $cur.dev_root 'AGENTS.md'
    $topOk = (Test-Path $top) -and ([IO.File]::ReadAllText($top)).Contains("laws-version $(Get-GrimdexStampVersion -GrimdexRoot $root)")
    if ($stale.Count -or -not $topOk) {
        Write-Host ("  Stamps: {0} of {1} project(s) out of date{2} — run: pwsh setup.ps1 -Update" -f $stale.Count, $wired.Count, $(if ($topOk) { '' } else { ', main level out of date' })) -ForegroundColor Yellow
    } else { Write-Host ("  Stamps: all {0} project(s) + main level current." -f $wired.Count) -ForegroundColor Green }
}
